[options]
addons_path = /mnt/extra-addons
db_host = $RENDER_DB_HOST
db_port = $RENDER_DB_PORT
db_user = $RENDER_DB_USER
db_password = $RENDER_DB_PASSWORD
db_name = tailor_style
admin_passwd = your_master_password_here
xmlrpc_port = 8069
log_level = info
