[options]
addons_path = /mnt/extra-addons
db_host = %(DB_HOST)s
db_port = %(DB_PORT)s
db_user = %(DB_USER)s
db_password = %(DB_PASSWORD)s
db_name = %(DB_NAME)s
admin_passwd = %(ADMIN_PASSWD)s
xmlrpc_port = 8069
log_level = info
